# This is a basic workflow to help you get started with Actions

name: Build and Test App

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Login to Docker Hub
        id: login
        run: docker login -u ${{ secrets.DOCKER_USER  }} -p ${{ secrets.DOCKER_PASSWORD }}

      # Runs a set of commands using the runners shell
      - name: Build the Docker image
        id: build
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USER  }}/flask-app-gh-actions
      - name: Push the Docker image
        id: push
        run: docker push ${{ secrets.DOCKER_USER  }}/flask-app-gh-actions
